all: ./bin/unitTest ./bin/functionalTest ./bin/executable

./documentation: ./bin/executable
	doxygen ./documentation/doxygen/.cfg
	cd ./documentation/latex && make
	cp ./documentation/latex/refman.pdf ./documentation/manual.pdf

./bin/executable: ./bin/base.so
	cd ./bin/ && g++ -std=c++11 -fPIC ../src/main.cpp -o ./executable -L . -lbase -Wl,-rpath .
	rm -rf ./bin/*.o *~

./bin/functionalTest: ./test/functional/main.cpp test/functional/FunctionalTests.cpp test/functional/FunctionalTests.h ./bin/base.so
	cd ./bin/ && g++ -std=c++11 -fPIC ../test/functional/main.cpp ../test/functional/FunctionalTests.cpp -o ./functionalTest -L . -lbase -Wl,-rpath .

./bin/unitTest: ./test/unit/main.cpp test/unit/unitTests.cpp test/unit/unitTests.h ./bin/unitBase.so
	cd ./bin/ && g++ -std=c++11 -fPIC ../test/unit/main.cpp ../test/unit/unitTests.cpp -o ./unitTest -L . -lunitBase -Wl,-rpath .

./bin/unitBase.so: ./bin/unitModel.o ./bin/unitFlow.o ./bin/unitSystem.o ./bin/base.so
	cd ./bin/ && g++ -std=c++11 -fPIC -shared ./unitModel.o ./unitFlow.o ./unitSystem.o -o ./libunitBase.so -L . -lbase -Wl,-rpath .

./bin/unitModel.o: ./test/unit/unitModel.cpp ./test/unit/unitModel.h
	cd ./bin/ && g++ -std=c++11 -fPIC -c ../test/unit/unitModel.cpp -o ./unitModel.o

./bin/unitFlow.o: ./test/unit/unitFlow.cpp ./test/unit/unitFlow.h
	cd ./bin/ && g++ -std=c++11 -fPIC -c ../test/unit/unitFlow.cpp -o ./unitFlow.o

./bin/unitSystem.o: ./test/unit/unitSystem.cpp ./test/unit/unitSystem.h
	cd ./bin/ && g++ -std=c++11 -fPIC -c ../test/unit/unitSystem.cpp -o ./unitSystem.o

./bin/base.so: ./bin/model.o ./bin/flow.o ./bin/system.o
	g++ -std=c++11 -fPIC -shared ./bin/model.o ./bin/flow.o ./bin/system.o -o ./bin/libbase.so

./bin/model.o: ./src/lib/ModelImplementation.cpp ./src/lib/ModelImplementation.h ./src/lib/Model.h ./bin/flow.o ./bin/system.o
	g++ -std=c++11 -fPIC -c ./src/lib/ModelImplementation.cpp -o ./bin/model.o

./bin/flow.o: ./src/lib/FlowImplementation.cpp ./src/lib/FlowImplementation.h ./src/lib/Flow.h ./bin/system.o
	g++ -std=c++11 -fPIC -c ./src/lib/FlowImplementation.cpp -o ./bin/flow.o

./bin/system.o: ./src/lib/SystemImplementation.cpp ./src/lib/SystemImplementation.h ./src/lib/System.h
	g++ -std=c++11 -fPIC -c ./src/lib/SystemImplementation.cpp -o ./bin/system.o

clean:
	rm -rf ./bin/*.o *~